/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   doccer_interpret.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lorbke <lorbke@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/02/17 15:28:58 by lorbke            #+#    #+#             */
/*   Updated: 2023/02/19 18:53:58 by lorbke           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "private_doccer.h" // create_doc, doc_heredoc
#include "parser.h" // t_ast
#include "lexer.h" // TOK_* defines
#include "../minishell.h" // t_status, ERR_* defines
#include <unistd.h> // unlink

t_status	doccer_interpret_unclosed_quotes(t_ast *ast, char **doc_input)
{
	if (!ast || !ast->token)
		return (ERR_SUCCESS);
	if (doccer_interpret_unclosed_quotes(ast->left, doc_input) != ERR_SUCCESS
		|| doccer_interpret_unclosed_quotes(ast->right, doc_input) != ERR_SUCCESS)
		return (ERR_GENERALERR);
	if (ast->token->desc == TOK_UNCLOSED_SQUOTE)
		return (create_doc(ast, doc_input, NULL));
	if (ast->token->desc == TOK_UNCLOSED_DQUOTE)
		return (create_doc(ast, doc_input, NULL));
	return (ERR_SUCCESS);
}

/* Returns the string generated by user input to close an unclosed branch
of the abstract syntax tree. */
t_status	doccer_interpret_unclosed_special(t_ast *ast, char **doc_input)
{
	if (!ast)
		return (ERR_SUCCESS);
	while (ast->right && ast->right->token->word)
		ast = ast->right;
	if (ast->token->desc == TOK_PIPE
		|| ast->token->desc == TOK_AND
		|| ast->token->desc == TOK_OR)
		return (create_doc(ast, 0, doc_input));
	return (ERR_SUCCESS);
}

t_status	doccer_delete_heredocs(t_ast *ast)
{
	int		ret_value;

	if (!ast || !ast->token)
		return (ERR_SUCCESS);
	ret_value = doccer_delete_heredocs(ast->left);
	ret_value = doccer_delete_heredocs(ast->right);
	if (ast->token->desc == TOK_REDIR_HEREDOC)
		ret_value = unlink(ast->right->token->word);
	if (ret_value == -1)
		return (ERR_GENERALERR);
	return (ERR_SUCCESS);
}

t_status	doccer_interpret_heredocs(t_ast *ast)
{
	if (!ast || !ast->token)
		return (ERR_SUCCESS);
	if (doccer_interpret_heredocs(ast->left) != ERR_SUCCESS
		|| doccer_interpret_heredocs(ast->right) != ERR_SUCCESS)
		return (ERR_GENERALERR);
	if (ast->token->desc == TOK_REDIR_HEREDOC)
		return (create_doc(ast, 1, NULL));
	return (ERR_SUCCESS);
}
